# Generated by Django 3.1.4 on 2021-02-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='starting_bid',
            field=models.FloatField(),
        ),
    ]
