# Generated by Django 3.1.4 on 2021-02-17 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210215_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='number_of_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
